image:
  repository: docker.io/duplicati/duplicati
  tag: latest@sha256:c6a2efddd86bdaf7c6927ea5c807986df7c0395581d061595db4884db2783ac5
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8200
        targetPort: 8200
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            DUPLICATI__WEBSERVICE_PASSWORD: "SuperSecretPassword"
            # SETTINGS_ENCRYPTION_KEY: "<real encryption key>"
            # DOTNET_SYSTEM_IO_DISABLEFILELOCKING: true

persistence:
  config:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true
